.github/scripts/get_target_deployed_tag.sh

- set initial tag for release notes

Docs: [AEA-0000] - set initial tag for release notes

---

.github/workflows/ci.yml
.github/workflows/release.yml

- :robot: Operational or Infrastructure Change
- Remove unused parameter for quality checks workflow

Fix: [AEA-0000]  - Fix quality checks workflow

---

.devcontainer/devcontainer.json
.gitallowed
.github/workflows/cdk_release_code.yml
.github/workflows/ci.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
.github/workflows/release_all_stacks.yml
.pre-commit-config.yaml
packages/cdk/bin/StatefulResourcesApp.ts
packages/cdk/resources/Cognito.ts
packages/cdk/stacks/StatefulResourcesStack.ts
packages/cdk/stacks/StatelessResourcesStack.ts
packages/cdk/stacks/UsCertsStack.ts

- do not use custom cognito domain for pull request
- use argjson to pass boolean to cdk.json
- update to latest quality checks
- add secret scanning config

Fix: [AEA-0000] - do not use cognito custom domain for pull request

---

packages/cdk/resources/CloudfrontDistribution.ts

- use separate folders for each stack cloudfront

Fix: [AEA-0000] - cloudfront logs per stack

---

.github/actions/mark_jira_released/action.yml
.github/actions/update_confluence_jira/action.yml
.github/workflows/delete_old_cloudformation_stacks.yml

- put the correct repo name in all role session names

Fix: [AEA-0000] - fix role session names

---

.github/workflows/link_dev_website.yml

- :robot: Operational or Infrastructure Change
This adds a workflow that should comment on the PR with a link to the dev deployment for this branch.

Build: [AEA-0000] - Add workflow to link to the PR deployment

---

.github/workflows/release_all_stacks.yml
packages/cdk/resources/Cloudfront/CloudfrontFunction.ts
packages/cdk/resources/CloudfrontBehaviors.ts
packages/cdk/stacks/StatelessResourcesStack.ts
packages/cloudfrontFunctions/src/cloudfront/index.js
packages/cloudfrontFunctions/src/genericS3FixedObjectUriRewrite.js
packages/cloudfrontFunctions/src/genericStripPathUriRewrite.js
packages/cloudfrontFunctions/src/s3StaticContentUriRewrite.js

Fix: [AEA-0000] - use a single kvs

---

packages/auth_demo/src/App.tsx
packages/cpt-ui/__tests__/AuthProvider.test.tsx
packages/cpt-ui/__tests__/SelectYourRolePage.test.jsx
packages/cpt-ui/app/selectyourrole/page.tsx
packages/cpt-ui/app/selectyourrole/test_data.tsx
packages/cpt-ui/constants/ui-strings/CardStrings.ts
packages/cpt-ui/context/AuthContext.tsx

- :sparkles: New Feature
Kris and I are working on similar features - merging my changes into his branch so that we are synchronised.

New: [AEA-0000] - Synchronise Jim and Kris

---

.github/workflows/deploy_website_content.yml
.github/workflows/link_dev_website.yml
.vscode/eps-prescription-tracker-ui.code-workspace
README.md
packages/cdk/resources/Cognito.ts
packages/cpt-ui/__tests__/SelectYourRolePage.test.tsx
packages/cpt-ui/app/searchforaprescription/page.tsx
packages/cpt-ui/app/selectyourrole/page.tsx
packages/cpt-ui/constants/ui-strings/HeaderStrings.ts
scripts/run_regression_tests.py

🎫 [AEA-4656](https://nhsd-jira.digital.nhs.uk/browse/AEA-4656) One role with access
🧪 Regression Tests: [PR-212](https://github.com/NHSDigital/electronic-prescription-service-api-regression-tests/pull/212)
🆔 User UID: 555043300081
:sparkles: New Feature
A user has one role with access to CPTS.

New: [AEA-4656] - One role with access

---

scripts/run_regression_tests.py

Fix: [AEA-0000] - Fix regression tests tag

---

.github/workflows/cdk_package_code.yml
.github/workflows/cdk_release_code.yml
.github/workflows/ci.yml
.github/workflows/create_release_notes.yml
.github/workflows/delete_old_cloudformation_stacks.yml
.github/workflows/dependabot_auto_approve_and_merge.yml
.github/workflows/deploy_website_content.yml
.github/workflows/link_dev_website.yml
.github/workflows/pr-link.yml
.github/workflows/pr_title_check.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
.github/workflows/release_all_stacks.yml
.github/workflows/run_regression_tests.yml
scripts/run_regression_tests.py

- use ubuntu 22.04 on github runners

Fix: [AEA-0000] - use ubuntu 22.04 on github runners

---

packages/cdk/resources/Cognito.ts

- fix callback url for auth demo

Fix: [AEA-0000] - fix callback url for auth demo

---

.github/workflows/pull_request.yml
.github/workflows/release.yml
.github/workflows/release_all_stacks.yml

-  adds skippable regressions and disables it in INT

Chore: [AEA-0000] - adds skippable regressions and disables it in INT

---

packages/cpt-ui/src/components/prescriptionSearch/PrescriptionIdSearch.tsx
packages/cpt-ui/src/context/AccessProvider.tsx

The label wasn't associated with the text input box, which is not good for WCAG. Adds a tag to link them together.
Also, for some reason my pre commit hook wouldn't let me commit without linting a completely unrelated file. So that's here too

Fix: [AEA-0000] - Associate label with input

---

.github/scripts/get_current_dev_tag.sh
.github/scripts/get_target_deployed_tag.sh

- fix getting deployed tag for release notes

Fix: [AEA-0000] - fix getting deployed tag for release notes

---

.gitallowed

Unblocks other branches by adding both endpoint variants to gitallowed file

Fix: [AEA-0000] - Unblocks other branches fixing gitallowed file

---

.github/workflows/pull_request.yml
packages/prescriptionListLambda/src/services/patientDetailsLookupService.ts
packages/prescriptionListLambda/src/services/prescriptionsLookupService.ts
packages/prescriptionListLambda/tests/test_prescriptionsLookupService.test.ts

- correct joining of paths for URLs

Fix: [AEA-0000] - correct joining of paths for URL

---

.github/workflows/ci.yml

Fix: [AEA-0000] - fix the qa pds endpoint

---

.github/workflows/ci.yml

- fix pds endpoint in ci build

Fix: [AEA-0000] - fix pds endpoint in ci build

---

packages/cpt-ui/src/styles/header.scss

changed text colour when highlighted

Fix: [AEA-0000] - changed text colour

---

packages/cpt-ui/__tests__/MessageHistoryCard.test.tsx
packages/cpt-ui/src/components/prescriptionDetails/MessageHistoryCard.tsx
packages/prescriptionListLambda/src/utils/responseMapper.ts
packages/prescriptionListLambda/tests/mockObjects.ts
packages/prescriptionListLambda/tests/test_responseMapper.test.ts

- Updates extension uri's in prescription list lambda
- Temporary removes dosage instructions from history card ([AEA-5487](https://nhsd-jira.digital.nhs.uk/browse/AEA-5487))

Fix: [AEA-0000] - Fix extension uri's

---

.gitallowed

Add gitallowed requirements for AEA-5519 branch.

Fix: [AEA-5519] - Add gitallowed

---

.github/workflows/run_regression_tests.yml

Fix: [AEA-0000] - new regression test tag

---

packages/cdk/resources/ukRegionLogGroups.ts
packages/cdk/resources/usRegionLogGroups.ts
packages/cdk/stacks/StatelessResourcesStack.ts

- use a custom name for policy

Fix: [AEA-0000] - use custom name for policy
